# test_cases.py
sample_inputs = [
"Hi, my name is John Doe, I'm in room 205. My lunch never arrived and I'm really hungry.",
"This is Jane Smith in room 304. My room is freezing cold and I've asked for an extra blanket three times already!",
"The nurse on duty last night was very rude to me. I want to speak to a manager.",
"I need a pillow for my visitor in room 205.",
"My visitor's badge was denied at reception.",
"The room lights are flickering in 102.",
"There's a strange smell in room 210.",
"My IV line is leaking in room 317.",
"The toilet in my room is not flushing.",
"I have not received my medication this morning.",
"My food tray has the wrong meal (I'm vegetarian).",
"The TV in room 203 does not work.",
"Noise from the hallway is keeping me awake all night.",
"I need help adjusting my bed, it is stuck.",
"My room door lock is broken.",
"The air conditioning is too strong in room 110.",
"I was double-billed for my hospital stay.",
"I left my phone charger at home, can I get one?",
"My room hasn't been cleaned today.",
"The call bell is not working in room 409.",
"I need assistance walking to the bathroom.",
"The nurse did not show up for my scheduled medication.",
"My visitor was not allowed after visiting hours.",
"I found a billing error on my invoice.",
"The food was cold and undercooked.",
"There is mold in the bathroom.",
"My discharge papers haven't been prepared yet.",
"I need a translator for my family when the doctor visits.",
"I need extra pillows, please deliver one to room 207.",
"The lights in my corridor flicker when someone uses the elevator.",
"My oxygen monitor is beeping non-stop.",
"I was not given proper dietary info for my allergy.",
"My room smells like cigarettes.",
"The wheelchair left in hall is blocking access.",
"The nurse gave me the wrong dosage yesterday.",
"My lab results haven't been updated in the portal.",
"The elevator is out of order on the 3rd floor.",
"I was charged for a service I did not receive.",
"I need extra bed sheets for my guest bed.",
"The window in my room won't close properly.",
"My medication was taken away and not returned.",
"The phone in the room has no dial tone.",
"I need to reschedule my appointment due to hospital delay.",
"The soap dispenser is empty in the bathroom.",
"I need a decaf tea instead of regular tea.",
"My dressing change was missed today.",
"The heating in the physiotherapy room is not working.",
"I think my chart has wrong allergy info.",
"The cafeteria ran out of vegetarian options today.",
"The visiting family can't find parking - can you help?",
"The IV pole is missing wheel and is unstable."
]
